package com.example.dilfoods.model;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.example.dilfoods.convertor.LocalDateTimeConverter;
import lombok.Data;

import java.time.LocalDateTime;

@Data
@DynamoDBTable(tableName = "InventoryHistory")
public class InventoryHistory {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String itemId;

    @DynamoDBAttribute
    private int stockLevel;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    private LocalDateTime timestamp;
}